// Code generated by protoc-gen-go.
// source: user.proto
// DO NOT EDIT!

/*
Package user is a generated protocol buffer package.

It is generated from these files:
        user.proto

It has these top-level messages:
        User
        UserRef
        SignUpRequest
        SignInRequest
        UpdateProfileRequest
        GetUsersRequest
        GetUsersResponse
        ChangePasswordRequest
        StatusResponse
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_rpc "google/rpc"

import (
        context "golang.org/x/net/context"
        grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
        Uid      string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
        Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
        Username string `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
        Photo    []byte `protobuf:"bytes,4,opt,name=photo,proto3" json:"photo,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type UserRef struct {
        Uid string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *UserRef) Reset()                    { *m = UserRef{} }
func (m *UserRef) String() string            { return proto.CompactTextString(m) }
func (*UserRef) ProtoMessage()               {}
func (*UserRef) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type SignUpRequest struct {
        Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
        Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
        Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
        Photo    []byte `protobuf:"bytes,7,opt,name=photo,proto3" json:"photo,omitempty"`
}

func (m *SignUpRequest) Reset()                    { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string            { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()               {}
func (*SignUpRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type SignInRequest struct {
        Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
        Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *SignInRequest) Reset()                    { *m = SignInRequest{} }
func (m *SignInRequest) String() string            { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()               {}
func (*SignInRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type UpdateProfileRequest struct {
        Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
        Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
        Photo    []byte `protobuf:"bytes,3,opt,name=photo,proto3" json:"photo,omitempty"`
}

func (m *UpdateProfileRequest) Reset()                    { *m = UpdateProfileRequest{} }
func (m *UpdateProfileRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateProfileRequest) ProtoMessage()               {}
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type GetUsersRequest struct {
        Ids      []*UserRef `protobuf:"bytes,1,rep,name=ids" json:"ids,omitempty"`
        Name     string     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
        Username string     `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
}

func (m *GetUsersRequest) Reset()                    { *m = GetUsersRequest{} }
func (m *GetUsersRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUsersRequest) ProtoMessage()               {}
func (*GetUsersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetUsersRequest) GetIds() []*UserRef {
        if m != nil {
                return m.Ids
        }
        return nil
}

type GetUsersResponse struct {
        Users []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
}

func (m *GetUsersResponse) Reset()                    { *m = GetUsersResponse{} }
func (m *GetUsersResponse) String() string            { return proto.CompactTextString(m) }
func (*GetUsersResponse) ProtoMessage()               {}
func (*GetUsersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetUsersResponse) GetUsers() []*User {
        if m != nil {
                return m.Users
        }
        return nil
}

type ChangePasswordRequest struct {
        OldPassword string `protobuf:"bytes,1,opt,name=old_password,json=oldPassword" json:"old_password,omitempty"`
        NewPassword string `protobuf:"bytes,2,opt,name=new_password,json=newPassword" json:"new_password,omitempty"`
}

func (m *ChangePasswordRequest) Reset()                    { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string            { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()               {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type StatusResponse struct {
        Ack    bool               `protobuf:"varint,1,opt,name=ack" json:"ack,omitempty"`
        Status *google_rpc.Status `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *StatusResponse) Reset()                    { *m = StatusResponse{} }
func (m *StatusResponse) String() string            { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()               {}
func (*StatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *StatusResponse) GetStatus() *google_rpc.Status {
        if m != nil {
                return m.Status
        }
        return nil
}

func init() {
        proto.RegisterType((*User)(nil), "user.User")
        proto.RegisterType((*UserRef)(nil), "user.UserRef")
        proto.RegisterType((*SignUpRequest)(nil), "user.SignUpRequest")
        proto.RegisterType((*SignInRequest)(nil), "user.SignInRequest")
        proto.RegisterType((*UpdateProfileRequest)(nil), "user.UpdateProfileRequest")
        proto.RegisterType((*GetUsersRequest)(nil), "user.GetUsersRequest")
        proto.RegisterType((*GetUsersResponse)(nil), "user.GetUsersResponse")
        proto.RegisterType((*ChangePasswordRequest)(nil), "user.ChangePasswordRequest")
        proto.RegisterType((*StatusResponse)(nil), "user.StatusResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for UserService service

type UserServiceClient interface {
        SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*StatusResponse, error)
        SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*StatusResponse, error)
        UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*StatusResponse, error)
        GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error)
        ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type userServiceClient struct {
        cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
        return &userServiceClient{cc}
}

func (c *userServiceClient) SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
        out := new(StatusResponse)
        err := grpc.Invoke(ctx, "/user.UserService/SignUp", in, out, c.cc, opts...)
        if err != nil {
                return nil, err
        }
        return out, nil
}

func (c *userServiceClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
        out := new(StatusResponse)
        err := grpc.Invoke(ctx, "/user.UserService/SignIn", in, out, c.cc, opts...)
        if err != nil {
                return nil, err
        }
        return out, nil
}

func (c *userServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
        out := new(StatusResponse)
        err := grpc.Invoke(ctx, "/user.UserService/UpdateProfile", in, out, c.cc, opts...)
        if err != nil {
                return nil, err
        }
        return out, nil
}

func (c *userServiceClient) GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error) {
        out := new(GetUsersResponse)
        err := grpc.Invoke(ctx, "/user.UserService/GetUsers", in, out, c.cc, opts...)
        if err != nil {
                return nil, err
        }
        return out, nil
}

func (c *userServiceClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
        out := new(StatusResponse)
        err := grpc.Invoke(ctx, "/user.UserService/ChangePassword", in, out, c.cc, opts...)
        if err != nil {
                return nil, err
        }
        return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
        SignUp(context.Context, *SignUpRequest) (*StatusResponse, error)
        SignIn(context.Context, *SignInRequest) (*StatusResponse, error)
        UpdateProfile(context.Context, *UpdateProfileRequest) (*StatusResponse, error)
        GetUsers(context.Context, *GetUsersRequest) (*GetUsersResponse, error)
        ChangePassword(context.Context, *ChangePasswordRequest) (*StatusResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
        s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
        in := new(SignUpRequest)
        if err := dec(in); err != nil {
                return nil, err
        }
        if interceptor == nil {
                return srv.(UserServiceServer).SignUp(ctx, in)
        }
        info := &grpc.UnaryServerInfo{
                Server:     srv,
                FullMethod: "/user.UserService/SignUp",
        }
        handler := func(ctx context.Context, req interface{}) (interface{}, error) {
                return srv.(UserServiceServer).SignUp(ctx, req.(*SignUpRequest))
        }
        return interceptor(ctx, in, info, handler)
}

func _UserService_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
        in := new(SignInRequest)
        if err := dec(in); err != nil {
                return nil, err
        }
        if interceptor == nil {
                return srv.(UserServiceServer).SignIn(ctx, in)
        }
        info := &grpc.UnaryServerInfo{
                Server:     srv,
                FullMethod: "/user.UserService/SignIn",
        }
        handler := func(ctx context.Context, req interface{}) (interface{}, error) {
                return srv.(UserServiceServer).SignIn(ctx, req.(*SignInRequest))
        }
        return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
        in := new(UpdateProfileRequest)
        if err := dec(in); err != nil {
                return nil, err
        }
        if interceptor == nil {
                return srv.(UserServiceServer).UpdateProfile(ctx, in)
        }
        info := &grpc.UnaryServerInfo{
                Server:     srv,
                FullMethod: "/user.UserService/UpdateProfile",
        }
        handler := func(ctx context.Context, req interface{}) (interface{}, error) {
                return srv.(UserServiceServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
        }
        return interceptor(ctx, in, info, handler)
}

func _UserService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
        in := new(GetUsersRequest)
        if err := dec(in); err != nil {
                return nil, err
        }
        if interceptor == nil {
                return srv.(UserServiceServer).GetUsers(ctx, in)
        }
        info := &grpc.UnaryServerInfo{
                Server:     srv,
                FullMethod: "/user.UserService/GetUsers",
        }
        handler := func(ctx context.Context, req interface{}) (interface{}, error) {
                return srv.(UserServiceServer).GetUsers(ctx, req.(*GetUsersRequest))
        }
        return interceptor(ctx, in, info, handler)
}

func _UserService_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
        in := new(ChangePasswordRequest)
        if err := dec(in); err != nil {
                return nil, err
        }
        if interceptor == nil {
                return srv.(UserServiceServer).ChangePassword(ctx, in)
        }
        info := &grpc.UnaryServerInfo{
                Server:     srv,
                FullMethod: "/user.UserService/ChangePassword",
        }
        handler := func(ctx context.Context, req interface{}) (interface{}, error) {
                return srv.(UserServiceServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
        }
        return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
        ServiceName: "user.UserService",
        HandlerType: (*UserServiceServer)(nil),
        Methods: []grpc.MethodDesc{
                {
                        MethodName: "SignUp",
                        Handler:    _UserService_SignUp_Handler,
                },
                {
                        MethodName: "SignIn",
                        Handler:    _UserService_SignIn_Handler,
                },
                {
                        MethodName: "UpdateProfile",
                        Handler:    _UserService_UpdateProfile_Handler,
                },
                {
                        MethodName: "GetUsers",
                        Handler:    _UserService_GetUsers_Handler,
                },
                {
                        MethodName: "ChangePassword",
                        Handler:    _UserService_ChangePassword_Handler,
                },
        },
        Streams:  []grpc.StreamDesc{},
        Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
        // 456 bytes of a gzipped FileDescriptorProto
        0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
        0x10, 0xc5, 0x71, 0x9a, 0x86, 0x71, 0x53, 0xa2, 0x25, 0x85, 0xc8, 0x3d, 0x10, 0xf6, 0x14, 0x71,
        0x70, 0xa5, 0x00, 0x27, 0x8e, 0x15, 0xaa, 0x7a, 0x41, 0x95, 0xa3, 0xdc, 0x80, 0xca, 0x8d, 0xa7,
        0xa9, 0x45, 0xd8, 0xdd, 0xee, 0xda, 0xe4, 0x0f, 0xf2, 0xc3, 0xd0, 0xee, 0x7a, 0x1d, 0xdb, 0xc4,
        0x88, 0xde, 0x66, 0xe7, 0xe3, 0xbd, 0xe7, 0x99, 0x27, 0x03, 0x14, 0x0a, 0x65, 0x24, 0x24, 0xcf,
        0x39, 0xe9, 0xeb, 0x38, 0x7c, 0xbd, 0xe1, 0x7c, 0xb3, 0xc5, 0x0b, 0x29, 0xd6, 0x17, 0x2a, 0x4f,
        0xf2, 0x42, 0xd9, 0x32, 0xfd, 0x0e, 0xfd, 0x95, 0x42, 0x49, 0xc6, 0xe0, 0x17, 0x59, 0x3a, 0xf5,
        0x66, 0xde, 0xfc, 0x79, 0xac, 0x43, 0x42, 0xa0, 0xcf, 0x92, 0x9f, 0x38, 0xed, 0x99, 0x94, 0x89,
        0x49, 0x08, 0x43, 0x0d, 0x67, 0xf2, 0xbe, 0xc9, 0x57, 0x6f, 0x32, 0x81, 0x23, 0xf1, 0xc0, 0x73,
        0x3e, 0xed, 0xcf, 0xbc, 0xf9, 0x49, 0x6c, 0x1f, 0xf4, 0x1c, 0x8e, 0x35, 0x7e, 0x8c, 0xf7, 0x7f,
        0x53, 0xd0, 0x47, 0x18, 0x2d, 0xb3, 0x0d, 0x5b, 0x89, 0x18, 0x1f, 0x0b, 0x54, 0x79, 0xc5, 0xe9,
        0x75, 0x70, 0xf6, 0x5a, 0x9c, 0x21, 0x0c, 0x45, 0xa2, 0xd4, 0x8e, 0xcb, 0xd4, 0xe9, 0x71, 0xef,
        0xbd, 0x9e, 0xe3, 0xba, 0x9e, 0x2b, 0x4b, 0x79, 0xcd, 0x1c, 0x65, 0x1d, 0xde, 0xfb, 0x07, 0x7c,
        0xaf, 0x09, 0x4f, 0xbf, 0xc2, 0x64, 0x25, 0xd2, 0x24, 0xc7, 0x1b, 0xc9, 0xef, 0xb3, 0x2d, 0xfe,
        0x0f, 0xde, 0xa1, 0x95, 0x56, 0x32, 0xfd, 0xba, 0xcc, 0x3b, 0x78, 0x71, 0x85, 0xb9, 0xde, 0x9c,
        0x72, 0xc0, 0x6f, 0xc0, 0xcf, 0x52, 0x35, 0xf5, 0x66, 0xfe, 0x3c, 0x58, 0x8c, 0x22, 0x73, 0xe2,
        0x72, 0xb5, 0xb1, 0xae, 0x3c, 0xf5, 0x60, 0xf4, 0x03, 0x8c, 0xf7, 0x1c, 0x4a, 0x70, 0xa6, 0x90,
        0xcc, 0xe0, 0x48, 0xd7, 0x1d, 0x0d, 0xd4, 0x68, 0x6c, 0x81, 0x7e, 0x83, 0xb3, 0xcb, 0x87, 0x84,
        0x6d, 0xf0, 0xa6, 0xdc, 0x84, 0xd3, 0xf7, 0x16, 0x4e, 0xf8, 0x36, 0xbd, 0xad, 0x16, 0x66, 0x3f,
        0x3e, 0xe0, 0xdb, 0xd4, 0x75, 0xea, 0x16, 0x86, 0xbb, 0xdb, 0xd6, 0x4e, 0x03, 0x86, 0x3b, 0xd7,
        0x42, 0xbf, 0xc0, 0xe9, 0xd2, 0xf8, 0xb3, 0x92, 0x34, 0x06, 0x3f, 0x59, 0xff, 0x30, 0x70, 0xc3,
        0x58, 0x87, 0xe4, 0x1d, 0x0c, 0xac, 0x87, 0x0d, 0x40, 0xb0, 0x20, 0x91, 0x75, 0x77, 0x24, 0xc5,
        0x3a, 0x2a, 0xa7, 0xcb, 0x8e, 0xc5, 0xef, 0x1e, 0x04, 0x5a, 0xfe, 0x12, 0xe5, 0xaf, 0x6c, 0x8d,
        0xe4, 0x23, 0x0c, 0xac, 0xe5, 0xc8, 0x4b, 0xfb, 0x6d, 0x0d, 0x03, 0x86, 0x93, 0x32, 0xd9, 0x90,
        0x40, 0x9f, 0xb9, 0xb1, 0x6b, 0x56, 0x1f, 0xab, 0x4c, 0xd4, 0x39, 0x76, 0x09, 0xa3, 0x86, 0x49,
        0x48, 0x58, 0x2e, 0xf4, 0x80, 0x73, 0x3a, 0x41, 0x3e, 0xc1, 0xd0, 0xdd, 0x89, 0x9c, 0xd9, 0x9e,
        0x96, 0x37, 0xc2, 0x57, 0xed, 0x74, 0x35, 0xfc, 0x19, 0x4e, 0x9b, 0xe7, 0x22, 0xe7, 0xb6, 0xf7,
        0xe0, 0x11, 0xbb, 0x34, 0xdc, 0x0d, 0xcc, 0xdf, 0xe2, 0xfd, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
        0xdb, 0xdb, 0x00, 0x11, 0x5a, 0x04, 0x00, 0x00,
}
