export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const FETCH_AVAILABLE_USERS_REQUEST = 'FETCH_AVAILABLE_USERS_REQUEST'
export const FETCH_AVAILABLE_USERS_SUCCESS = 'FETCH_AVAILABLE_USERS_SUCCESS'
export const FETCH_AVAILABLE_USERS_FAILURE = 'FETCH_AVAILABLE_USERS_FAILURE'

export const ADD_USER = 'ADD_USER'
export const REMOVE_USER = 'REMOVE_USER'

export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE'
