// Code generated by protoc-gen-go.
// source: user.proto
// DO NOT EDIT!

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	User
	SignUpRequest
	Token
	SignInRequest
	UpdateProfileRequest
	GetUsersRequest
	GetUsersResponse
	ChangePasswordRequest
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Uid      string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Username string `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	Photo    []byte `protobuf:"bytes,4,opt,name=photo,proto3" json:"photo,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SignUpRequest struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Photo    []byte `protobuf:"bytes,7,opt,name=photo,proto3" json:"photo,omitempty"`
}

func (m *SignUpRequest) Reset()                    { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string            { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()               {}
func (*SignUpRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Token struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *Token) Reset()                    { *m = Token{} }
func (m *Token) String() string            { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()               {}
func (*Token) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type SignInRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *SignInRequest) Reset()                    { *m = SignInRequest{} }
func (m *SignInRequest) String() string            { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()               {}
func (*SignInRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type UpdateProfileRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Photo    []byte `protobuf:"bytes,3,opt,name=photo,proto3" json:"photo,omitempty"`
}

func (m *UpdateProfileRequest) Reset()                    { *m = UpdateProfileRequest{} }
func (m *UpdateProfileRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateProfileRequest) ProtoMessage()               {}
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type GetUsersRequest struct {
	Uids     []string `protobuf:"bytes,1,rep,name=uids" json:"uids,omitempty"`
	Name     string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Username string   `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
}

func (m *GetUsersRequest) Reset()                    { *m = GetUsersRequest{} }
func (m *GetUsersRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUsersRequest) ProtoMessage()               {}
func (*GetUsersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type GetUsersResponse struct {
	Users []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
}

func (m *GetUsersResponse) Reset()                    { *m = GetUsersResponse{} }
func (m *GetUsersResponse) String() string            { return proto.CompactTextString(m) }
func (*GetUsersResponse) ProtoMessage()               {}
func (*GetUsersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type ChangePasswordRequest struct {
	OldPassword string `protobuf:"bytes,1,opt,name=old_password,json=oldPassword" json:"old_password,omitempty"`
	NewPassword string `protobuf:"bytes,2,opt,name=new_password,json=newPassword" json:"new_password,omitempty"`
}

func (m *ChangePasswordRequest) Reset()                    { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string            { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()               {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*SignUpRequest)(nil), "user.SignUpRequest")
	proto.RegisterType((*Token)(nil), "user.Token")
	proto.RegisterType((*SignInRequest)(nil), "user.SignInRequest")
	proto.RegisterType((*UpdateProfileRequest)(nil), "user.UpdateProfileRequest")
	proto.RegisterType((*GetUsersRequest)(nil), "user.GetUsersRequest")
	proto.RegisterType((*GetUsersResponse)(nil), "user.GetUsersResponse")
	proto.RegisterType((*ChangePasswordRequest)(nil), "user.ChangePasswordRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for AuthService service

type AuthServiceClient interface {
	SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*Token, error)
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*Token, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := grpc.Invoke(ctx, "/user.AuthService/SignUp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := grpc.Invoke(ctx, "/user.AuthService/SignIn", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthService service

type AuthServiceServer interface {
	SignUp(context.Context, *SignUpRequest) (*Token, error)
	SignIn(context.Context, *SignInRequest) (*Token, error)
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.AuthService/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SignUp(ctx, req.(*SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.AuthService/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUp",
			Handler:    _AuthService_SignUp_Handler,
		},
		{
			MethodName: "SignIn",
			Handler:    _AuthService_SignIn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

// Client API for UserService service

type UserServiceClient interface {
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/user.UserService/UpdateProfile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error) {
	out := new(GetUsersResponse)
	err := grpc.Invoke(ctx, "/user.UserService/GetUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/user.UserService/ChangePassword", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	UpdateProfile(context.Context, *UpdateProfileRequest) (*google_protobuf.Empty, error)
	GetUsers(context.Context, *GetUsersRequest) (*GetUsersResponse, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*google_protobuf.Empty, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/UpdateProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUsers(ctx, req.(*GetUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateProfile",
			Handler:    _UserService_UpdateProfile_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _UserService_GetUsers_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _UserService_ChangePassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x53, 0xc1, 0x6e, 0xd4, 0x30,
	0x10, 0xdd, 0x6c, 0xb2, 0x65, 0x99, 0xb4, 0x50, 0x99, 0xb6, 0x8a, 0x52, 0x21, 0x05, 0x9f, 0x7a,
	0x40, 0xa9, 0xb4, 0x70, 0xe3, 0x84, 0x50, 0xb5, 0xea, 0xad, 0x4a, 0xc9, 0x0d, 0xa8, 0x52, 0x32,
	0xcd, 0x46, 0xa4, 0x76, 0x1a, 0x3b, 0xac, 0xf8, 0x55, 0xbe, 0x06, 0xd9, 0x5e, 0x67, 0x93, 0x68,
	0x17, 0xc1, 0x6d, 0x66, 0xfc, 0xfc, 0xde, 0xcc, 0x1b, 0x1b, 0xa0, 0x15, 0xd8, 0xc4, 0x75, 0xc3,
	0x25, 0x27, 0x9e, 0x8a, 0xc3, 0xf3, 0x82, 0xf3, 0xa2, 0xc2, 0x4b, 0x5d, 0xbb, 0x6f, 0x1f, 0x2e,
	0xf1, 0xb1, 0x96, 0xbf, 0x0c, 0x84, 0x7e, 0x03, 0x2f, 0x15, 0xd8, 0x90, 0x63, 0x70, 0xdb, 0x32,
	0x0f, 0x9c, 0xc8, 0xb9, 0x78, 0x9e, 0xa8, 0x90, 0x10, 0xf0, 0x58, 0xf6, 0x88, 0xc1, 0x54, 0x97,
	0x74, 0x4c, 0x42, 0x98, 0x2b, 0x4a, 0x5d, 0x77, 0x75, 0xbd, 0xcb, 0xc9, 0x09, 0xcc, 0xea, 0x15,
	0x97, 0x3c, 0xf0, 0x22, 0xe7, 0xe2, 0x30, 0x31, 0x09, 0x7d, 0x82, 0xa3, 0xdb, 0xb2, 0x60, 0x69,
	0x9d, 0xe0, 0x53, 0x8b, 0x42, 0x76, 0xb4, 0xce, 0x1e, 0xda, 0xe9, 0x88, 0x36, 0x84, 0x79, 0x9d,
	0x09, 0xb1, 0xe6, 0x4d, 0x6e, 0x25, 0x6d, 0xbe, 0x95, 0x7c, 0xd6, 0x97, 0x7c, 0x0d, 0xb3, 0xcf,
	0xfc, 0x07, 0x32, 0x75, 0x2c, 0x55, 0xb0, 0xd1, 0x32, 0x09, 0x5d, 0x9a, 0x8e, 0xae, 0x99, 0xed,
	0xa8, 0xaf, 0xee, 0xfc, 0x45, 0x7d, 0x3a, 0x54, 0xa7, 0x5f, 0xe0, 0x24, 0xad, 0xf3, 0x4c, 0xe2,
	0x4d, 0xc3, 0x1f, 0xca, 0x0a, 0xff, 0x85, 0x6f, 0x97, 0xa9, 0xdd, 0x14, 0x6e, 0x7f, 0x8a, 0x14,
	0x5e, 0x2e, 0x51, 0xaa, 0xdd, 0x88, 0x9e, 0x75, 0x6d, 0x99, 0x8b, 0xc0, 0x89, 0x5c, 0x75, 0x59,
	0xc5, 0xff, 0xbb, 0x25, 0xfa, 0x1e, 0x8e, 0xb7, 0xb4, 0xa2, 0xe6, 0x4c, 0x20, 0x89, 0x60, 0xa6,
	0xce, 0x0d, 0xb1, 0xbf, 0x80, 0x58, 0x3f, 0x21, 0x85, 0x49, 0xcc, 0x01, 0xfd, 0x0a, 0xa7, 0x9f,
	0x56, 0x19, 0x2b, 0xf0, 0x66, 0x33, 0xbc, 0x6d, 0xe9, 0x0d, 0x1c, 0xf2, 0x2a, 0xbf, 0xeb, 0x3c,
	0x32, 0xf3, 0xfa, 0xbc, 0xca, 0x2d, 0x52, 0x41, 0x18, 0xae, 0xef, 0x46, 0x36, 0xfa, 0x0c, 0xd7,
	0x16, 0xb2, 0x28, 0xc1, 0xff, 0xd8, 0xca, 0xd5, 0x2d, 0x36, 0x3f, 0xcb, 0xef, 0x48, 0xde, 0xc2,
	0x81, 0x79, 0x33, 0xe4, 0x95, 0x69, 0x65, 0xf0, 0x82, 0x42, 0xdf, 0x14, 0xf5, 0x8e, 0xe9, 0xc4,
	0xa2, 0xaf, 0x59, 0x1f, 0xdd, 0x6d, 0x77, 0x84, 0x5e, 0xfc, 0x76, 0xc0, 0x57, 0x93, 0x59, 0xad,
	0x2b, 0x38, 0x1a, 0x2c, 0x91, 0x84, 0x9b, 0xe9, 0x77, 0x6c, 0x36, 0x3c, 0x8b, 0xcd, 0x57, 0x8a,
	0xed, 0x57, 0x8a, 0xaf, 0xd4, 0x57, 0xa2, 0x13, 0xf2, 0x01, 0xe6, 0xd6, 0x56, 0x72, 0x6a, 0x18,
	0x46, 0xdb, 0x0b, 0xcf, 0xc6, 0x65, 0xe3, 0x3e, 0x9d, 0x90, 0x25, 0xbc, 0x18, 0xba, 0x4b, 0xce,
	0x0d, 0x76, 0xa7, 0xe7, 0xfb, 0xbb, 0xb8, 0x3f, 0xd0, 0x95, 0x77, 0x7f, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x5a, 0xf3, 0x2e, 0x60, 0x04, 0x04, 0x00, 0x00,
}
